test

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -71,26 +71,24 @@ jobs:
           VM_IP=$(gcloud compute instances describe spring-boot-vm --zone ${{vars.GOOGLE_ZONE}} --format='value(networkInterfaces[0].accessConfigs[0].natIP)')
           echo "VM_IP=$VM_IP" >> $GITHUB_ENV
           echo $VM_IP
-      
-      # Run app
+
+
+      # SSH and run application
       - name: SSH and run the new application
         uses: fifsky/ssh-action@master
         with:
-          command: | 
-            cd /tmp
-            ls -a
-          host: ${{env.VM_IP}}
-          username: ${{vars.SSH_USERNAME}}
+          host: ${{ env.VM_IP }}
+          user: ${{ vars.SSH_USERNAME }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
-          script: |
+          command: |
             sudo apt update
             sudo apt install -y docker.io
-            
+
             sudo systemctl stop docker
             sudo systemctl start docker
             sudo systemctl enable docker
-            
-            sudo docker rm ${{vars.DOCKER_CONTAINER_NAME}}
-            sudo docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{vars.DOCKER_ACCESS_TOKEN}}
-            sudo docker pull ${{secrets.DOCKER_USERNAME}}/${{vars.DOCKER_IMAGE_NAME}}:latest
-            sudo docker run -d -p 5000:5000 -e WEBSERVER_PORT=5000 --name ${{vars.DOCKER_CONTAINER_NAME}} ${{secrets.DOCKER_USERNAME}}/${{vars.DOCKER_IMAGE_NAME}}
+
+            sudo docker rm ${{ vars.DOCKER_CONTAINER_NAME }} || true # Added '|| true' to prevent the step from failing if the container does not exist
+            sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ vars.DOCKER_ACCESS_TOKEN }}
+            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/${{ vars.DOCKER_IMAGE_NAME }}:latest
+            sudo docker run -d -p 5000:5000 -e WEBSERVER_PORT=5000 --name ${{ vars.DOCKER_CONTAINER_NAME }} ${{ secrets.DOCKER_USERNAME }}/${{ vars.DOCKER_IMAGE_NAME }}
